# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('user_role', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=10)),
                ('class_lvl', models.CharField(max_length=10)),
                ('suspended', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Training_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_1', models.DateTimeField(verbose_name='laser_cut')),
                ('tr_2', models.DateTimeField(verbose_name='3d-print')),
                ('tr_3', models.DateTimeField(verbose_name='solder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Student')),
            ],
        ),
    ]
