# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20170721_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_dates',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Student', unique=True),
        ),
    ]
